version: 2 
jobs:       
  build:
    docker:
      - image: hello-world
    steps:
      - checkout
      - run:
          name: Hello World TEST
          command: "echo 'Hello World !!!'"
workflows:
  version: 2
  build_test:
    jobs:
      - build
